import { config } from "dotenv";

config({ path: "./.env", quiet: true });

export const {
  PORT,
  NODE_ENV,
  APP_NAME,
  DB_URI,
  SALT_ROUNDS,
  ENCRYPTION_KEY,
  APP_EMAIL,
  APP_EMAIL_PASSWORD,
  ACCESS_TOKEN_USER_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_USER_SECRET,
  REFRESH_TOKEN_EXPIRES_IN,
  ACCESS_TOKEN_ADMIN_SECRET,
  REFRESH_TOKEN_ADMIN_SECRET,
  WEB_CLIENT_ID,
  AWS_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME,
  AWS_PRE_SIGNED_URL_EXPIRES_IN,
} = process.env;
