import { config } from "dotenv";

config({ path: "./.env", quiet: true });

export const {
  PORT,
  NODE_ENV,
  APP_NAME,
  DB_URI,
  SALT_ROUNDS,
  ENCRYPTION_KEY,
  APP_EMAIL,
  APP_EMAIL_PASSWORD,
  ACCESS_TOKEN_USER_SECRET,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_USER_SECRET,
  REFRESH_TOKEN_EXPIRES_IN,
  ACCESS_TOKEN_ADMIN_SECRET,
  REFRESH_TOKEN_ADMIN_SECRET,
} = process.env;
